services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    working_dir: /app/frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"  # Use port from .env file
    environment:
      - NODE_ENV=development
      - VITE_NETWORK_ID=${VITE_NETWORK_ID}  # Use network ID from .env file
      - FRONTEND_PORT=${FRONTEND_PORT}  # Pass port to container
    restart: unless-stopped
    volumes:
      # For development mode only - comment these out for production
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
   # healthcheck:
   #   test: ["CMD", "wget", "--spider", "-q", "http://localhost:${FRONTEND_PORT}"]
   #   interval: 30s
   #   timeout: 10s
   #   retries: 3
   #   start_period: 5s
