services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    ports:
      - "9090:9090"  # Map host port 9090 to container port 9090
    environment:
      - NODE_ENV=development
      # Update these with your preferred network configuration
      - VITE_NETWORK_ID=1  # Mainnet by default
      # No need for RPC URL since we removed that requirement
    restart: unless-stopped
    volumes:
      # For development mode only - comment these out for production
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
