version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      # Update these with your preferred network configuration
      - VITE_NETWORK_ID=1  # Mainnet by default
      - VITE_RPC_URL=https://mainnet.infura.io/v3/YOUR-INFURA-KEY
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
