version: '3.8'

services:
  # Frontend service
  frontend:
    image: ghcr.io/michaelfisher1997/cosmic-lotto/cosmic-lotto-frontend:main
    pull_policy: always
    ports:
      - "80:3000"  # Map port 80 to the internal port 3000
    environment:
      - NODE_ENV=production
      # Update these with your preferred network configuration
      - VITE_NETWORK_ID=1  # Mainnet by default
      - VITE_RPC_URL=https://mainnet.infura.io/v3/YOUR-INFURA-KEY
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
