[phases.setup]
nixPkgs = ['nodejs-18_x', 'bun']
commands = [
  "chmod +x /app/.nixpacks/build.sh",
  "/app/.nixpacks/build.sh"
]

[start]
cmd = "cd /app/frontend && bun run dev -- --host 0.0.0.0 --port $PORT"

[build.args]
NODE_ENV = { required = false, default = "production" }
VITE_NETWORK_ID = { required = false, default = "1" }
VITE_RPC_URL = { required = true }

[build.environment]
NODE_ENV = "production"

[build.dockerfile]
copy = [
  "frontend/package*.json",
  "frontend/tsconfig*.json",
  "frontend/",
  "."
]

[build.settings]
memory = 1024
cpu = 1

[build.context]
base = "/app"
