# Base image with Node.js and Bun
[phases.setup]
nixPkgs = ["nodejs-18_x", "bun"]
aptPkgs = ["ca-certificates"]

# Install dependencies
[phases.install]
cmds = [
  "cd frontend && bun install",
  "cd frontend && bun add -d @esbuild-plugins/node-globals-polyfill @esbuild-plugins/node-modules-polyfill rollup-plugin-node-polyfills"
]

# Build the application
[phases.build]
cmds = ["cd frontend && bunx node static-build.js"]

# Start command (for static hosting, use serve)
[start]
cmd = "cd frontend && bunx serve -s dist -p $PORT"

# Environment variables
[variables]
NODE_ENV = "production"

# Configure Nixpacks to properly handle the frontend directory
[nixpacks]
plan-path = "./frontend"

# Environment variables for build
[env]
NODE_ENV = "production"
VITE_NETWORK_ID = { required = false, default = "1" }
